source("loader.R")

png(file = "plot4.png", width = 480, height = 480)
par(mfrow=c(2,2))	
plot(subdf$Time, subdf$Global_active_power, type = "l", xlab = "", ylab = "Global Active Power")
plot(subdf$Time, subdf$Voltage, type = "l", xlab = "datetime", ylab = "Global Active Power")
plot(subdf$Time, subdf$Sub_metering_1, type = "l", col = "black", xlab = "", ylab = "Energy sub metering")
lines(subdf$Time, subdf$Sub_metering_2, type="l", col="red")
lines(subdf$Time, subdf$Sub_metering_3, type="l", col="blue")
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lwd=2, col=c("black", "red", "blue"))
plot(subdf$Time, subdf$Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global Active Power")
dev.off()